### PR TITLE
Robertoschanges

### PR DESCRIPTION
**Pull request by rjavila**
This PR re-organizes the directory structure so that each Science Saturday has it's own folder. This is for Issue #13 .

### CODE REVIEW

**Comment by dborncamp** [comment]
Are we going to keep all of the data in a data directory or have the data for each event be in its `SS` directory?

**Comment by rjavila** [comment]
For now I've left all the data in one directory. Not really sure if I have a preference either way.

**Review by dborncamp — APPROVED** [review]
This looks good! Fix the conflicts and merge.

**Comment by rjavila** [comment]
I don't have write access. Hook me up @dborncamp

**Comment by dborncamp** [comment]
I already invited you as a collaborator, you haven't responded... https://github.com/dborncamp/ScienceSaturday/invitations

**Comment by dborncamp** [comment]
I can't change it in your fork...

**Pull request merged**
