### PR TITLE
Adding nicely formatted Beer table

### LINKED ISSUE #4: Add Table for Beer
The Beer data is in an acceptable form. Add a nice latex table to the paper.

### PR DESCRIPTION
**Pull request by dborncamp**
Fixes #4.

### CODE REVIEW

**Comment by sean-lockwood** [comment]
Cool trick with `beer.to_latex()`.  I'll have to remember that.
By the way, you can diff notebooks using [nbdime](http://nbdime.readthedocs.io).  It even has a nifty git-integration and html view.

**Review by sean-lockwood — APPROVED** [review]
Not sure if you intended to include all the LaTeX auxiliary files or not.

**Comment by jhunkeler** [comment]
Rendered table:

image

Does it look OK to you?

Also :+1: for deleting the TeX build artifacts from the repo.

**Comment by sean-lockwood** [comment]
I didn't look at the rendered table.  Yeah, columns shouldn't be center-justified.

**Comment by dborncamp** [comment]
I just added the whole folder so it could use some pruning. I also almost never use LaTex (I used Word wherever possible for papers) so I don't know what needs to be kept. Do we just need the `.tex` files or are there others that should be kept?

**Comment by dborncamp** [comment]
What should the justification in the columns be?

**Comment by sean-lockwood** [comment]
Text: left
numbers: right, but you have to give them with a fixed number of decimal places.

**Comment by dborncamp** [comment]
What do you mean `give them with a fixed number of decimal places` I'm not sure what you mean or how to do that...

**Comment by sean-lockwood** [comment]
I mean:  Make every integer end in ".0" to match the one decimal point in e.g. "0.5".
However, left-justifying this particular dataset seems to align everything well.

```python
one_decimal = lambda x: '{:.1f}'.format(x)
print (beer.to_latex(formatters={b: one_decimal for b in beer.columns[1:]}, 
                     float_format=one_decimal, column_format='rlrrrrrrrrrrrrrrrrrr'))
```

**Pull request merged**
